#!/bin/bash

# Get the list of staged files
files=$(git diff --name-only --cached --diff-filter=ACM | grep '\.scala$')

# Exit if there are no staged Scala files
if [[ -z "$files" ]]; then
    exit 0
fi

./sbtx 'set scalafmtFilter:="diff-dirty"' scalafmtAll "scalafixAll --diff-base main"

# Add the formatted files to the staging area
git add $files

exit 0
